### ISSUE TITLE
Create Genre Overview 

### ISSUE THREAD

**Issue by ReallyBoard123** [devhausleipzigacademy/camp10-midterm#38]
This page is reached when the user clicks on the "See All" link on the genre section on the homepage to select genres from a list of genres. Earlier, this was intended to be a full-page modal but later changed to a page layout for ease. You are still free to choose whichever route you are comfortable with.

When the user selects the genre, 1 ) the upcoming movie section on the home page, and 2) the movies page for now_playing will show only the movies from the selected genre

## Prerequisites 
- [x] #9 

## Tasks

- [x] Create an object that maps emojis to genres
- [x] Make each IconButton selectable
- [x] When selected is clicked again -> deselect
- [x] keep a count of selected genres

## Hints

The current API already has a list of genres. They have some 15 listed. We will only be using 12 of them. Check the ones that are missing. Each genre would have an id, an emoji, and a name.

Should the selected genre be persisted via a global store?

## Figma Resources
https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/midterm?type=design&node-id=18%3A560&mode=design&t=poNoiZC2HH4cKdlU-1
