### ISSUE TITLE
Create Movies Page

### ISSUE THREAD

**Issue by ReallyBoard123** [devhausleipzigacademy/camp10-midterm#39]
This page shows us all the movies from now_playing. now_playing returns 20 movies, which we want to store using pagination, with each page showing four movies. The first four movies are on page 1, the next four on page 2, and so on... 

## Prerequisites
- [x] #11 
- [x] #21 

## Tasks

- [x] Use the tmdb API to show the movies from now_playing.
- [x] Divide the movies into five pages
- [x] onClick to a page number, display the next four movies

## Resources

https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/midterm?type=design&node-id=226%3A211&mode=design&t=poNoiZC2HH4cKdlU-1

## Hint

Think about how will you manage the movies when the genre filter will be active.

**Comment by JanHendryk** [comment]
Ready
