### ISSUE TITLE
Create Cast and Crew Page

### ISSUE THREAD

**Issue by ReallyBoard123** [devhausleipzigacademy/camp10-midterm#46]
This is the cast and crew page that hosts two tabs. Clicking on the tab switches the content. 

## Prerequisites

- [ ] #41 
- [x] #20 

## Tasks

- [x] use the [headless UI tabs](https://headlessui.com/react/tabs)
- [x] Create the cast tab that displays the information from the cast
- [x] Create the crew tab that displays the information from crew
- [x] hide the scrollbar

## Optional
- [ ] can experiment with transitions: 
- [ ] When clicked on the crew, the content could slide in from right to left
- [ ] When clicked on the cast, the content could slide in from left to right

## Resources

https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/midterm?type=design&node-id=226%3A89&mode=design&t=85Psolq3XTgpwjoz-1
