### ISSUE TITLE
Create Seat Selection Page

### ISSUE THREAD

**Issue by ReallyBoard123** [devhausleipzigacademy/camp10-midterm#47]
This is the page where the users can select the seats. When clicked on a seat, the information is displayed on the #29 

## Tasks

- [x] Make the screen ([yellow bar](https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/midterm?type=design&node-id=3%3A217&mode=design&t=85Psolq3XTgpwjoz-1))
- [x] Create the seat layout (hint: "first" and "last" rows have 1 less seat on both corners)
- [x] Create the bottom legend
- [x] Mount the #29 

## Hints

- [x] Seat layout has to be created considering the data structure. Each seat needs an id that Zustand will use to be able to send the information to our tickets page !

## Resources

https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/midterm?type=design&node-id=3%3A217&mode=design&t=85Psolq3XTgpwjoz-1
