### ISSUE TITLE
Get booked seats

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp10-midterm#63]
## Prerequisites

- [ ] #59 

## Tasks

- [ ] Write a GET route and controller for getting back the seats
- [ ] check ich the endpoint is working by sending a request.
- [ ] Get all Seats from the Database which are booked on a given movie, date and time
- [ ] send back all booked seats to the client and mark the seats as booked when they are not available
